### ISSUE TITLE
Large portrait images gets distorted to landscape size

### ISSUE THREAD

**Issue by regs01** [darktrojan/betterimageviewer#5]
The problem emerged with recent version. Once i try to zoom them in they get distorted to landscape orientation.

![2017-11-10 20-02-01 2017-11-02 12-49-39 jpg jpeg 2988 x 5312 - 21 - mozilla fir](https://user-images.githubusercontent.com/10468217/32669621-34db42ec-c652-11e7-8a0c-1749551829c2.png)
![2017-11-10 20-02-23 2017-11-02 12-49-39 jpg jpeg 2988 x 5312 - mozilla firefox](https://user-images.githubusercontent.com/10468217/32669627-392432f0-c652-11e7-82ad-fe57828698af.png)

image for test
https://yadi.sk/i/E-vJU6ZV3Pb5hs

**Comment by artofwalls** [comment]
It works correctly in my pre-Quantum Firefox

**Comment by marsjaninzmarsa** [comment]
Cannot reproduce.

**Comment by regs01** [comment]
was fixed in version 18

**Comment by walllable** [comment]
I still have the issue. Here's the specific image, if it helps. 
![20190729_133230](https://user-images.githubusercontent.com/10066958/62069386-26ae0f00-b206-11e9-9640-5dfaf776ff2e.jpg)

**Comment by darktrojan** [comment]
I'm aware this is a bug. No need to post any more pictures.

It's also a bug that's hard to fix, because there isn't a good way to detect images like this.

**Comment by regs01** [comment]
It actually turned that version 18 didn't fix it. I just forgot to open original image when checking.

But version 20 does fix it for sure. The only problem is that Waterfox didn't find the update from AMO, so had to uninstall/reinstall it.

So @walllable, make sure you have updated version 20.

**Comment by regs01** [comment]
Well, 21 breaks it again.

**Comment by regs01** [comment]
Can you bring back version 20, or at least provide xpi. It's not on AMO.
